spring.application.name=tech



spring.datasource.url=jdbc:postgresql://ep-falling-lake-am9j5s80.c-5.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mnSrNaM8skY5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true